### ISSUE TITLE
세계 시계

### ISSUE THREAD

**Issue by palrang22** [Kim-Dong-Hyeon/KimnJangWatch#1]
## 어떤 기능인가요?

> 탭바 페이지 1 - 세계시계

## 작업 상세 내용
 
- [x] 세계 시계 메인 View - TableView 구현
- [x] 세계 시계 ViewModel 구현
- [ ] 네비게이션 아이템 '편집' 클릭시 TableView Cell 삭제
- [x] 네비게이션 아이템 '+' 페이지 View 구현
- [x] '+' 페이지 ViewModel 구현

**Comment by soobeen27** [comment]
네비게이션 아이템 '편집' 클릭시 TableView Cell 삭제
 -> cell 스와이프 하여 삭제로 변경
